### PR TITLE
kyber/v3 and XORKeyStream 

### PR DESCRIPTION
**Pull request by ivn-nz**
Hopefully, I have done that correctly.
I took the branch from the pull request (that updates to kyber/v3) and fixed the XORkeyStream. Additionally, I had to update some test that seemed to be broken. I think it is due to updating the kyber library. It just needed a few changes.

Two changes:
-crypto.go: uses a function from kyber library which in its current version have a proper XORkeyStream in place.
-Nonetheless, I fixed the error in XORKeyStream from util.go, if it wants to be used instead of the one in kyber.

### CODE REVIEW

**Comment by cretz** [comment]
Can you merge master back into your branch and resolve conflicts? Then I'll merge

**Comment by ivn-nz** [comment]
I haven't merged into my master branch because I have modified the fork quite a lot to do other things I've been testing that I think they are not necessary for the protocol itself. Therefore, the branch pr/4 holds an older version of what i have now.

It would be great if you could just merge that branch. I took a look to the conflict and it is just 1, in which "my" crypto_test.go does not have the tests provided by a previous merge from Ne0nd0g. I think you can just merge altogether.

**Comment by cretz** [comment]
I meant merge this master. Git and GitHub don't allow merging a conflict. I will have to do the conflict resolution and push myself when I get a chance, no prob.

**Comment by cretz** [comment]
I have some time to look at this now! Will merge and maybe make a minor syntax adjustment or two...thanks!

**Pull request merged**
